import Head from "next/head";
import Link from "next/link";
import Categories from "~/components/Categories";
import ImageCanvas from "~/components/ImageCanvas";
import Section from "~/components/Section";
import { Card, CardContent, CardHeader, CardTitle } from "~/components/ui/card";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex-1 gap-2 flex bg-slate-100 dark:bg-neutral-800 pb-1">
        <div className="flex-[7_7_0%] bg-white dark:bg-neutral-900 border-slate-300 dark:border-neutral-600 border rounded-sm">
          <ImageCanvas />
        </div>
        <div className="flex-[3_3_0%] bg-white dark:bg-neutral-900 border-slate-300 dark:border-neutral-600 border rounded-sm relative">
          <Section />
        </div>
      </div>
    </>
  );
}
