import Head from "next/head";
import Link from "next/link";
import Categories from "~/components/Categories";
import { Card, CardContent, CardHeader, CardTitle } from "~/components/ui/card";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <div>
          <Card className="mx-auto mt-10 max-w-xl rounded-2xl dark:bg-neutral-900">
            <CardHeader className="space-y-1 text-center">
              <CardTitle className="text-[32px]">Please mark your interests!</CardTitle>
              <CardTitle className="pt-2 text-[16px] font-normal">We will keep you notified.</CardTitle>
            </CardHeader>
            <CardContent className="md:px-16">
              <Categories />
            </CardContent>
          </Card>
        </div>
      </main>
    </>
  );
}
